name: Build and test pull request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.4.21255.9
    - name: Setup .NET Core for Azure Function worker
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build with dotnet
      run: dotnet build src --configuration Release
    - name: Test
      run: dotnet test src /p:CollectCoverage=true /p:CoverletOutput=coverage /p:CoverletOutputFormat=lcov
